[package]
name = "my_demo"
version = "0.1.0"
authors = ["David Komer <david.komer@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
awsm_web = { path = "../../crate", features = ["all", "debug_log"]}
nalgebra = "0.20.0"
futures = "0.3.4"
lazy_static = "1.4.0"
lut_parser = "2.1.1"
wasm-bindgen = "0.2.59"
wasm-logger = { version = "0.2.0", optional = true }
gloo-events = "0.1.1"
gloo-timers = "0.2.1"
futures-signals = "0.3.15"
matches = "0.1.8"
js-sys = "0.3.36"
cfg-if = "0.1.10"
paste = "0.1.7"
log = "0.4.8"
num-traits = "0.2.11"
num-derive = "0.3.0"
serde = { version = "1.0.104", features = ["derive"] }
serde_repr = "0.1.5"
serde-wasm-bindgen = "0.1.3"
serde_json = "1.0.48"
wee_alloc = { version = "0.4.5", optional = true }
wasm-bindgen-futures= "0.4.9"
console_error_panic_hook = { version = "0.1.6", optional = true }
web-sys = { version = "0.3.36", features = [
  'Document',
  'Element',
  'HtmlElement',
  'Node',
  'Window',
  'ShadowRoot',
  'Performance',
  'Storage',
  'CustomEvent',
  "MouseEvent",
  "HtmlAnchorElement",
  "HtmlElement",
  "HtmlCanvasElement",
  "CssStyleDeclaration",
  "Node",
  "Window",
  "Performance",
  'console'
] }

[features]
default = ["wee_alloc"]
ts_test = []
quiet = []
dev = ["wee_alloc", "wasm-logger", "console_error_panic_hook"]
